### ISSUE TITLE
Call to undefined method 

### ISSUE THREAD

**Issue by wontroba666** [iMi-digital/magento2-store-switch-all-store-views#8] opened 2022-04-14 09:35 UTC
Error: Call to undefined method Magento\Store\ViewModel\SwitcherUrlProvider::isEnabled() in /public_html/vendor/imi/magento2-store-switch-all-store-views/view/frontend/templates/switch/languages.phtml:10 

any help ?

**Comment by amenk** [comment] 2022-04-14 09:49
@wontroba666 Can you reproduce this in a plain Magento installation? Which Magento Version are you using?

**Comment by wontroba666** [comment] 2022-04-14 10:36
2.4.2

**Comment by amenk** [comment] 2022-04-14 10:39
Is it a plain installation?
If you could debug this, it would be great - we would be happy about a pull request, if it is a issue in the module.

**Comment by wontroba666** [comment] 2022-04-22 11:43
no, it works fine on a new installation

unfortunately, it does not work on my current store

i do not know why ;(

**Comment by amenk** [comment] 2022-04-22 12:41
Hard to saw from afar. What did you try to debug it? Did you clean all caches and so on?

Here are some pointers:

Do you have the recent version of the plugin (can you compare the file here https://github.com/iMi-digital/magento2-store-switch-all-store-views/blob/master/view/frontend/templates/switch/languages.phtml)

Can you check what's in the variable `$viewModel` ?

The view model is created here https://github.com/iMi-digital/magento2-store-switch-all-store-views/blob/591e0286899a0b7ee30dde446f50492df44cabc5/view/frontend/layout/default.xml#L21

Can you check if this layout XML is applied in your case? Did you maybe create the block in another way or does it have another name or was moved?

**Comment by janssensjelle** [comment] 2023-05-31 07:11
I think this is due to a custom theme. We are experiencing the same issue with our theme (MageSuite). Adding the view_model argument did the trick

**Comment by amenk** [comment] 2023-05-31 08:38
@janssensjelle thanks for the confirmation :-)

@wontroba666 are you using a custom theme? Were you able to fix this?
I will close this issue, if you think this is a general issue of the module, let us know.

**Closed as not planned** 2023-05-31 08:38 UTC
